- Skins/Skin.ini/en.md
See: https://github.com/Quaver/Quaver/pull/328
> Added StageReceptorPadding

- Skins/Skin.ini/en.md
Duplicate Row, TimingLineColor is already shown in line 57.
> Remove duplicate row

- Skins/Skin.ini/en.md
https://github.com/Quaver/Quaver/pull/697
> Skin.ini: add CenterCursor

- Skins/Skin.ini/en.md
https://github.com/Quaver/Quaver/pull/705
> Skin.ini: add DeadNoteColor

- Gameplay/it.md
- Ranking/Criteria/it.md
- Ranking/Process/it.md
- Ranking/it.md
- Rules/it.md
- Skins/Interface/it.md
- Skins/Keys/it.md
- Skins/SFX/it.md
- Skins/Skin.ini/it.md
- Skins/it.md
- it.md
Translation in Italian of every part of the wiki beside "Legal"
> Translation in Italian

- Gameplay/de.md
- Ranking/Criteria/de.md
- Ranking/Process/de.md
- Rules/de.md
- de.md
We didn't feel like translating the legal and skin stuff (because to be honest who wants to do that), so you'll have to live without them.
Contributors:
@ElectroYan
@IceDynamix
> German localization

- Rules/en.md
- Rules/it.md
Fixed a typo in `en.md` and changed/improved some italian sentences in `it.md`
> Eng typo & italian translation

- Rules/en.md
Line 23 had a sentence missing.
fixes #17
> Minor fix in Rules

- Skins/Keys/en.md
> Fixed wrong example paths

- FAQ/de.md
- Gameplay/de.md
- Gameplay/it.md
- Ranking/Criteria/en.md
FAQ update for de.md, otherwise fixed various things in all languages
> Various updates

- FAQ/en.md
- Gameplay/en.md
- Ranking/Criteria/en.md
Updated FAQ to represent questions asked in the open beta instead of alpha.
Updated Gameplay page and added Modifier descriptions.
Updated metadata rules and SV rules, and specified what map length means in Ranking Criteria.
> Updates and Rewording

- en-US/gameplay/README.md
- en-US/ranking/criteria.md
Updated outdated information regarding gameplay and ranking criteria wiki pages
> Gameplay/Criteria Fixes

- en-US/faq/README.md
Should work well out of the box now.
> FAQ: update Linux audio latency section

- Legal/Privacy/en.md
- en-US/faq/README.md
- en-US/ranking/criteria.md
- en-US/ranking/process.md
Minor fixes to outdated or incorrect information.
These (combined with my previous pull request) should fix the issues #84-#90 as well as #75 and #72.
> Minor fixes/additions

- en-US/editor/editor_functions.md
Added descriptions for new resnapping features and livemapping feature. Also fixed some typos/outdated information.
> Added descriptions for the new editor functions

- en-US/api/README.md
- en-US/api/leaderboard.md
- en-US/api/maps.md
- en-US/api/mapsets.md
- en-US/api/miscellaneous.md
- en-US/api/multiplayer.md
- en-US/api/playlists.md
- en-US/api/scores.md
- en-US/api/users.md
- en-US/api/web.md
Most information provided by AiAe. There might be some mistakes regarding parameters, but should be mostly complete.
> Add API Documentation

- en-US/editor/plugins.md
Figured this would be relevant, add if you feel so
> Add PatternMaster in plugin list

- en-US/skins/README.md
- Fixed the directory of the pages under the documents since I changed names of the files and the TOC.ini too.
- Added another question under FAQ.
- Trimmed Default Skins vs. User Skins
- Added more details under **How to create a skin?**
- Some adjustments under **Uploading to Steam Workshop**
> Updates and changes in README.md

- en-US/skins/skin.ini.md
Added some skin.ini values for Main Menu(navigation button alpha), Song Select(mapset panel alpha), and Results Screen Skinning values.
> Add new skin.ini values used in Canary

- en-US/skins/clientinterface.md
Added 2 new skinnable files in Main Menu Skinning and Results Screen Skinning.
> New skinnable files from canary for skinning wiki.

- en-US/skins/clientinterface.md
Updated the notes of `note-visualizer.png`
I have to triple check when I get really tired while doing this.
> Re-update the notes of note-visualizer.png in the Client Interface.

- example_plugins/shift_notes_right_x_lanes/plugin.lua
Make use of the "new" action batch feature and remove comment about the bug fixed with https://github.com/Quaver/Quaver/pull/3330
> Update note shifter plugin

- en-US/skins/gameplayinterface.md
Janko: suggested size for grades should be 60x60
> Suggested size for grades

- en-US/ranking/criteria.md
Move avoiding high resolution from guidelines to rules with set values.
Add upper limits for bg/banner resolution
Add upper limit for banner file size
> Add more detailed banner and background clauses

- en-US/skins/gameplayinterface.md
- en-US/skins/skin.ini.md
The features can be seen in this pull request: https://github.com/Quaver/Quaver/pull/3581
> Adding the judgement counter features in skinning category

- en-US/skins/skin.ini.md
> add SongTimeProgressPositionAtTop description

- en-US/skins/skin.ini.md
> add hit error alpha description

- en-US/skins/clientinterface.md
/Results/grade-large-grade.png -> /Grades/grade-large-grade.png
> Correct filepath for results screen grades

- en-US/ranking/README.md
- en-US/ranking/criteria.md
- en-US/ranking/glossary.md
Following the Ranking Supervisor Meeting held on 10/19/2024
> Ranking Criteria Update

- en-US/skins/gameplayinterface.md
- en-US/skins/sfx.md
- en-US/skins/skin.ini.md
Documentation for:
https://github.com/Quaver/Quaver/pull/4482
https://github.com/Quaver/Quaver/pull/4473
https://github.com/Quaver/Quaver/pull/4465
https://github.com/Quaver/Quaver/pull/4463
> Add documentation for features added in 1.7.0.2
